[meta title:"Dijkstra_viz_V1" description:"Short description of your project" /]

[Header
  title:"Dijkstra_viz_V1"
  subtitle:"Welcome to Idyll. Open index.idl to start writing"
  author:"Josh Pollock"
  authorLink:"https://idyll-lang.github.io" /]

This is an Idyll file. Write text
as you please in here. To add interactivity,
you can add  different components to the text.

Here is how you can use a variable:

[var name:"exampleVar" value:5 /]

[Range min:0 max:10 value:exampleVar /]
[Display value:exampleVar /]

```js
var code = true;
var foo = bar;
```

And here is a custom component:

[CustomComponent /]

You can use standard html tags if a
component with the same name
doesn't exist.

* *markdown* syntax is supported.

[var name:"state" value:0 /]

[CustomD3Component state:state /]
[button onClick:`state++`]
  Click Me.
[/button]

[CircleWave /]
[GraphUI /]
[GraphUI /]

[var name:"color" value:"#000" /]

[Force nodeColor:`color` /]

[Button onClick:`color === '#000' ? color = '#ff0000' : color = '#000' `]
Toggle Color
[/Button]